source: /
output: /

collections_config:
  pages:
    name: Səhifələr
    path: /
    parser: html
    filter:
      base: none
      include:
        - "index.html"
    config:
      url: /index.html
      text_key: title
      allowed_views:
        - visual
      editor:
        default_item_editor: visual

# Digər faylları gizlətmək üçün
common_config:
  filter:
    base: none
    exclude:
      - admin
      - content.json
      - firebase.json
      - README.md
      - CNAME
      - cloudcannon.config.yml

paths:
  static: /
  uploads: videos
  dam_uploads: videos

editor:
  default_item_editor: visual
