backend:
  name: github
  repo: azhunmmc-source/azhunholding
  branch: main

media_folder: "videos"
public_folder: "videos"

collections:
  - name: "pages"
    label: "Səhifələr"
    files:
      - name: "home"
        label: "Ana Səhifə"
        file: "index.html"
        fields:
          - {label: "Başlıq", name: "title", widget: "string"}
          - {label: "Təsvir", name: "description", widget: "text"}
